Поддержка php 74
Topface/oauth2-apple pull request #3
Opened 2020-12-23 13:06 UTC by KiranTomar

2020-12-23 14:19 UTC, mdovgilev approved these changes

2020-12-28 15:43 UTC, KiranTomar commented on test/src/Provider/AppleTest.php
>  		    ->withClaim('sub', 'test')
```suggestion
		    ->set('sub', 'test')
```

2021-02-24 14:03 UTC, ShishkinAR approved these changes

2021-02-24 14:13 UTC, ShishkinAR requested changes

2021-02-24 14:13 UTC, ShishkinAR commented on CHANGELOG.md
> +
```suggestion
### Fixed
- Support php 7.4

```

2021-02-24 14:18 UTC, merged